# Generated by Django 4.2.5 on 2023-11-13 06:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='receipe_name', unique=True),
        ),
    ]
