# Generated by Django 4.2.5 on 2023-11-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_receipe_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='slug',
        ),
        migrations.AlterField(
            model_name='receipe',
            name='receipe_description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='receipe_image',
            field=models.FileField(upload_to=''),
        ),
    ]
