# Generated by Django 4.2.5 on 2023-11-14 05:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_remove_receipe_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='receipe_name', unique=True),
        ),
    ]
