# Generated by Django 4.2.5 on 2023-11-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_receipe_receipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_description',
            field=models.TextField(max_length=1000),
        ),
    ]
