# Generated by Django 4.2.5 on 2023-11-15 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='id',
        ),
        migrations.AlterField(
            model_name='amount',
            name='receipe_amount',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WebApp.receipe'),
        ),
    ]
