# Generated by Django 4.2.5 on 2023-11-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_remove_amount_id_alter_amount_receipe_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='amount',
        ),
    ]
