# Generated by Django 4.2.5 on 2023-11-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_amount',
            field=models.IntegerField(default=200),
        ),
    ]
